INFO - access -  logging __init__
INFO - access -  logging get_simple_logger
INFO - access -  logging __del__
INFO - access -  access connect ok
ERROR - access -   error in sql_cur_fetchone
Traceback (most recent call last):
  File "C:/lwz/softproject/py/Gynecology Fetal kidney From Prof Zeng/access.py", line 78, in sql_cur_fetchone
    return self.__dbcur__.fetchone()
  File "C:\lwz\Program Files (x86)\Python36-32\lib\site-packages\pypyodbc.py", line 1937, in fetchone
    check_success(self, ret)
  File "C:\lwz\Program Files (x86)\Python36-32\lib\site-packages\pypyodbc.py", line 1007, in check_success
    ctrl_err(SQL_HANDLE_STMT, ODBC_obj.stmt_h, ret, ODBC_obj.ansi)
  File "C:\lwz\Program Files (x86)\Python36-32\lib\site-packages\pypyodbc.py", line 985, in ctrl_err
    raise Error(state,err_text)
pypyodbc.Error: ('HY010', '[HY010] [Microsoft][ODBC 驱动程序管理器] 函数序列错误')
